import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getHomePageData, getLabelAssets } from "@/lib/cms/cms";
import { Divider } from "../components/components";
import Footer from "../components/Footer";
import { AvatarDiv } from "../components/HeroSection";
import Header from "../components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const t = await getLabelAssets();
  const homePageData = await getHomePageData();
  const twitterUrl = homePageData.Header.socials.find(
    (e) => e.icon === "x",
  )?.url;

  return (
    <html lang="en">
      <body className="overflow-x-hidden">
        <Header data={homePageData.Header} t={t} />
        <main
          className={`${geistSans.variable} ${geistMono.variable} antialiased ${geistSans.className} font-geist-sans mx-auto min-h-screen max-w-150 scroll-smooth flex flex-col lg:pt-16 pt-12 text-primary font-medium -tracking-[0.02em] p-5  `}
        >
          <AvatarDiv data={homePageData.Header} t={t} />
          {children}
          <Divider />
          <Footer t={t} twitterUrl={twitterUrl} />
        </main>
      </body>
    </html>
  );
}
