services:
  next-app:
    container_name: next-app
    env_file:
      - .env
    build:
      context: ./
      dockerfile: prod.Dockerfile
      args:
        ENV_VARIABLE: ${ENV_VARIABLE}
        NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    restart: always
    ports:
      - 3023:3000
    volumes:
      - portfolio_db_data:/app/data

volumes:
  portfolio_db_data:
